apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-api
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: "wayaks.eastus.cloudapp.azure.com"
    http:
      paths:
      - path: /simple-api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: simple-api
            port:
              number: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: simple-api
        image: wayaks.azurecr.io/simple-api:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: DataConfig__Response
          value: "Hello from East US Simple API"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-api
spec:
  ports:
  - port: 80
  selector:
    app: simple-api